import PIXI from "pixi.js";

// Generated by GitHub Copilot to replace the missing drawStar function from pixi.js
// This function draws a star shape using the PIXI.Graphics object.
export function drawStar(
  g: PIXI.Graphics,
  x: number,
  y: number,
  points: number,
  radius: number,
  innerRadius: number = radius / 2,
  rotation = 0
) {
  const angleStep = (Math.PI * 2) / points;
  g.moveTo(
    x + Math.cos(rotation) * radius,
    y + Math.sin(rotation) * radius
  );

  for (let i = 1; i <= points * 2; i++) {
    const isOuter = i % 2 === 0;
    const r = isOuter ? radius : innerRadius;
    const angle = rotation + i * (angleStep / 2);
    g.lineTo(
      x + Math.cos(angle) * r,
      y + Math.sin(angle) * r
    );
  }

  g.closePath();
}
